apiVersion: v1
kind: Service
metadata:
  name: apache2
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: apache2                  
